# Generated by Django 5.0.1 on 2024-02-03 14:06

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField(default=datetime.datetime.now)),
                ('from_location', models.CharField(max_length=50)),
                ('to_location', models.CharField(max_length=50)),
                ('seat_count', models.PositiveIntegerField(default=60)),
                ('booked_seats', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FlightStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_time', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flightbooking.flight')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flightbooking.flightstatus'),
        ),
    ]
